name: Check formatting and typecheck

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  uv-check:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Enable caching
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run cargo format check
        working-directory: ./lib/rollingwins
        run: cargo fmt -- --check

      - name: Run static analysis
        run: uvx ruff check

      - name: Run type checker
        run: uvx ty check

      - name: Minimize uv cache
        run: uv cache prune --ci